name: example build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: my_examples

    - name: Set up ROS2 workspace
      uses: ichiro-its/ros2-ws-action/setup@v1.0.0
      with:
        distro: 'humble'

    - name: Build the workspace
      uses: ichiro-its/ros2-ws-action/build@v1.0.0